<?php


$title = 'Deletar Contato';
$url   = $this->url('agenda', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que quer deletar 
    <?= $this->escapeHtml($agenda->nome) ?>
    <?= $this->escapeHtml($agenda->sobrenome) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $agenda->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Sim" />
    <input type="submit" class="btn btn-success" name="del" value="Não" />
</div>
</form>